name: Coleta de Preços

on:
  workflow_dispatch:

jobs:
  run_scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Executar o script Python
      run: |
        python scraper.py

    - name: Adicionar arquivos gerados ao commit
      run: |
        git add buscape_resultados.csv
        git commit -m "Adicionando resultados coletados"
        git push https://$GH_TOKEN@github.com/Christian311091/Coleta_Precos.git HEAD:main
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
